### ISSUE TITLE
CSS and JS fix

### ISSUE THREAD

**Issue by SpenGietz** [miwst/portfolio2#4]
The page looks great and the project slider is awesome. I think it would look good if you could get the slider to not scroll up or down but still sideways and show the captions still. Or for each image, on hover, you could show the name of the project as a tooltip. Besides that everything seems fine.

**Comment by miwst** [comment]
I added a tooltip.  I also fixed the scrollbars on the large-screen projects-div so that only the horizontal scrollbar is visible and all thumbnails are scaled correctly.
